### PR TITLE
Add terminationGracePeriodSeconds

### PR DESCRIPTION
**Pull request by IneyMickey**
I'm lacking terminationGracePeriodSeconds value

So here's my solution

### CODE REVIEW

**Comment by IneyMickey** [comment]
@d3adb5 - Hello!
Could you please review?

**Review by d3adb5 — APPROVED** [review]
LGTM!

**Comment by IneyMickey** [comment]
@d3adb5 - Can I ask you to merge?

**Comment by IneyMickey** [comment]
Thanks for fast release!

**Pull request merged**
