### PR TITLE
feat: upgrade pdb to v1

### PR DESCRIPTION
**Pull request by aslafy-z**
Optionally upgrade PDB to v1 if supported by the target cluster.

### CODE REVIEW

**Comment by stakater-user** [comment]
@aslafy-z Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/application/commit/87fc07e0ba2b7565ac9e7aa9ab7a772c415ffea9/checks) has Failed!

**Comment by rasheedamir** [comment]
@aslafy-z can you plz update the readme as well and add changelog? I will get the pipeline fixed

**Comment by stakater-user** [comment]
@aslafy-z Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/application/commit/b467260c380bf5d7ade5606bedb510f88a978208/checks) has Failed!

**Comment by aslafy-z** [comment]
@rasheedamir do you want me to do add something else?

**Comment by stakater-user** [comment]
@aslafy-z Validation Successful

**Comment by aslafy-z** [comment]
Let me know if you need anything else from my side @rasheedamir :call_me_hand:

**Comment by rasheedamir** [comment]
Looks great @aslafy-z ! will approve and merge it

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
